export const ErrorCode = {
  UNKNOWN: "UNKNOWN",
  CONFIG: "CONFIG_ERROR",
  VALIDATION: "VALIDATION_ERROR",
  RPC: "RPC_ERROR",
  NETWORK: "NETWORK_ERROR",
  DEADLINE: "DEADLINE_EXCEEDED",
  SLIPPAGE: "SLIPPAGE_EXCEEDED",
  INSUFFICIENT_LIQUIDITY: "INSUFFICIENT_LIQUIDITY",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  TRANSACTION: "TRANSACTION_FAILED",
  REDACTION: "REDACTION_BLOCKED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];